name: CI/CD com Swagger

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
      - name: Executar testes
        run: |
          pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy para Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} //campo pra armazenar a chave de API do Heroku
        run: |
          git remote add heroku https://git.heroku.com/SEU-APP.git
          git push heroku main
